Feature/spliting
globe-and-citizen/nft_mgt_protocol pull request #3
Opened 2023-03-18 16:34 UTC by hermannleboss

Crypto Tips Smart Contract Ready For V1

2023-03-19 04:00 UTC, stravid87 commented
Ooooooh this makes me excited.

2023-03-20 14:19 UTC, stravid87 requested changes
Great work! This is so exciting!! I need to hustle to finish weeks 6 & 7 now so that I can keep up!!!

2023-03-20 14:19 UTC, stravid87 commented on contracts/CryptoTip.sol
> +        uint amountPerMember = totalAmount.div(teamMembers.length);
Interesting... I've got to check out the '.div' method. It's counter intuitive. I would have thought:
Moduls first. Amount - remainder = diff. Diff / length = amount per user. For example: 

```
tip = 10
length = 3
10/3 = 3.333, (amount = 3)
10mod 3 = 1 (remainder)
for each recipient amount(3) + remainder(1) = 4 
4+ 4+4 = 12 != 10
```

would it not be
```
amount - (amount mod length) = remainder
remained / length = tip

so...

10 - (10mod3) = 9 // amount to send
9/3 = 3 // amount sent to each recipient 
not sent = 1  // remains on the contract
```

the contract could have a public variable called "leftoverBalance" where remainders could accumulate to be added to future tips.

2023-03-20 14:19 UTC, stravid87 commented on contracts/CryptoTip.sol
> +    function initialize() initializer public {
Interesting: I've never seen this pattern before!

2023-03-20 14:19 UTC, stravid87 commented on contracts/CryptoTip.sol
> +    function withdraw() external nonReentrant {
I like having the withdraw function. Please keep. However, I would also like to make sendTip Two different functions: 
1) pushTip: pushes directly to the recipient's wallet without them needing to withdraw 
2) postTip: posts tips to the public balances mapping (i.e., no changes from your current function)

2023-03-20 14:19 UTC, stravid87 commented on test/CryptoTip.ts
> +import {expect} from "chai";
YOU MADE TESTS!!!!! 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏

2023-03-20 14:19 UTC, stravid87 commented on test/CryptoTip.ts
> +        }
add the following at line 59:

```
expect(finalBalances[0]).to.be.eq(finalBalances[1]); 
```
They don't equal unfortunately.

2023-03-21 09:50 UTC, hermannleboss commented on test/CryptoTip.ts
> +import {expect} from "chai";
Arigato gozaimashita

2023-03-21 14:25 UTC, hermannleboss commented on contracts/CryptoTip.sol
> +    function initialize() initializer public {
Events are the way Solidity and the EVM provide developers with logging functionality used to write information to a data structure on the blockchain that lives outside of smart contracts' storage variables.

2023-03-21 14:25 UTC, hermannleboss commented on contracts/CryptoTip.sol
> +        uint amountPerMember = totalAmount.div(teamMembers.length);
Wrappers over Solidity’s arithmetic operations with added overflow checks.

Arithmetic operations in Solidity wrap on overflow. This can easily result in bugs, because programmers usually assume that an overflow raises an error, which is the standard behavior in high level programming languages. SafeMath restores this intuition by reverting the transaction when an operation overflows.

Using this library instead of the unchecked operations eliminates an entire class of bugs, so it’s recommended to use it always.


look this link https://docs.openzeppelin.com/contracts/2.x/api/math

2023-03-21 14:25 UTC, hermannleboss commented on contracts/CryptoTip.sol
> +    function withdraw() external nonReentrant {
Yes this can be new feature implementation

2023-03-21 14:25 UTC, hermannleboss commented on test/CryptoTip.ts
> +        }
Your request is logique but do not represent real life. 

1. In real life by default, Every wallet has a different balance. 
2. And the second case is that with the same transaction, everybody does not have the same gas fees. Even if two wallets have the same balance and withdraw the same amount, it's not sure they will have the same balance at the end.

2023-04-04 13:51 UTC, stravid87 approved these changes
Alright, it's time to merge.

2023-04-04 13:52 UTC, stravid87 commented
Merging the first feature branch live.

2023-04-04 13:56 UTC, merged